schema_version: 1

context:
  version: "0.8.0"

package:
  name: holm
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/h/holm/holm-${{ version }}.tar.gz
    sha256: 84ee0582062d9d666f6ec8a6a5756cd8b71fcf5b8ea50103972e8de1cd30f0a3

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - fastapi >=0.115.12
    - fasthx >=3.0.1
    - htmy >=0.8.2
    - lxml >=6.0.0
    - python-multipart >=0.0.20

tests:
  - python:
      imports:
        - holm
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/volfpeter/holm
  summary: Web development framework that brings the Next.js developer experience to Python, built on FastAPI, htmy, and FastHX.

extra:
  recipe-maintainers:
    - davidbrochart
